CHANGELOG.md
facade/src/main/scala/react/semanticui/elements/button/Button.scala
facade/src/main/scala/react/semanticui/elements/icon/Icon.scala
facade/src/main/scala/react/semanticui/elements/label/Label.scala
facade/src/main/scala/react/semanticui/elements/label/LabelDetail.scala
facade/src/main/scala/react/semanticui/modules/sidebar/Sidebar.scala
facade/src/main/scala/react/semanticui/modules/sidebar/package.scala
facade/src/main/scala/react/semanticui/package.scala
facade/src/test/scala/react/semanticui/modules/sidebar/SidebarTests.scala

Support sidebar

---

facade/src/main/scala/react/semanticui/elements/divider/Divider.scala
facade/src/main/scala/react/semanticui/elements/divider/package.scala
facade/src/main/scala/react/semanticui/elements/header/Header.scala
facade/src/main/scala/react/semanticui/package.scala
facade/src/test/scala/react/semanticui/elements/divider/DividerTests.scala

Add divider wrapper

---

CHANGELOG.md
facade/src/main/scala/react/semanticui/modules/checkbox/Checkbox.scala
facade/src/main/scala/react/semanticui/modules/checkbox/package.scala
facade/src/main/scala/react/semanticui/package.scala
facade/src/test/scala/react/semanticui/modules/checkbox/CheckboxTests.scala

Add checkbox module

---

CHANGELOG.md
build.sbt
facade/src/main/scala/react/semanticui/elements/icon/Icon.scala
facade/src/main/scala/react/semanticui/elements/icon/package.scala

Upgrade to 0.85.0

---

build.sbt
project/plugins.sbt

Library udates

---

build.sbt
facade/src/main/scala/react/semanticui/package.scala
facade/src/test/scala/react/semanticui/elements/image/ImageTests.scala
facade/src/test/scala/react/semanticui/modules/sidebar/SidebarTests.scala

Updated react common

---

CHANGELOG.md
build.sbt
facade/src/main/scala/react/semanticui/elements/label/Label.scala
facade/src/main/scala/react/semanticui/elements/rail/Rail.scala
facade/src/main/scala/react/semanticui/elements/rail/package.scala
facade/src/main/scala/react/semanticui/modules/popup/Popup.scala
facade/src/test/scala/react/semanticui/elements/label/LabelTests.scala
facade/src/test/scala/react/semanticui/elements/rail/RailTests.scala

SUI update and added Rail component

---

CHANGELOG.md
build.sbt
demo/src/main/resources/dev.js
demo/src/main/scala/react/semanticui/demo/HomeComponent.scala
demo/yarn.lock
facade/src/main/scala/react/semanticui/toasts/SemanticToastContainer.scala
facade/src/main/scala/react/semanticui/toasts/package.scala
facade/src/test/scala/react/semanticui/toasts/ToastsTests.scala

Add facade for react-semantic-toasts

---

facade/src/main/scala/react/semanticui/collections/form/Form.scala
facade/src/main/scala/react/semanticui/collections/grid/Grid.scala
facade/src/main/scala/react/semanticui/package.scala
facade/src/test/scala/react/semanticui/elements/button/ButtonTests.scala

Support as for Form and Grid

---

.gitignore
build.sbt
facade/src/main/scala/react/semanticui/elements/button/Button.scala
facade/src/main/scala/react/semanticui/elements/header/Header.scala
facade/src/main/scala/react/semanticui/elements/list/ListHeader.scala
facade/src/main/scala/react/semanticui/elements/list/ListItem.scala
facade/src/main/scala/react/semanticui/modules/dropdown/DropdownItem.scala
facade/src/main/scala/react/semanticui/modules/modal/Modal.scala
facade/src/main/scala/react/semanticui/package.scala
facade/src/main/scala/react/semanticui/views/item/ItemHeader.scala
facade/src/test/scala/react/semanticui/elements/button/ButtonTests.scala
facade/src/test/scala/react/semanticui/elements/list/ListIconTests.scala
facade/src/test/scala/react/semanticui/elements/list/ListItemTests.scala
facade/src/test/scala/react/semanticui/modules/dropdown/DropdownItemTests.scala

For the moment, only the following components allow attribute passthrough:
- Modal
- Button
- Header
- ListHeader
- ListItem
- ItemHeader

Passthrough attributes (a few components).

---

facade/src/main/scala/react/semanticui/elements/icon/package.scala
facade/src/test/scala/react/semanticui/elements/icon/IconTests.scala

Some of the operations on Icon conflict with simple class accessors

Better semantics for operations on icons

---

facade/src/main/scala/react/semanticui/elements/icon/Icon.scala
facade/src/main/scala/react/semanticui/elements/icon/package.scala
facade/src/test/scala/react/semanticui/elements/icon/IconTests.scala

Support updating an Icon's clazz

---

facade/src/main/scala/react/semanticui/elements/button/Button.scala
facade/src/main/scala/react/semanticui/elements/button/package.scala

Use an enum for button's labelPosition

---

CHANGELOG.md
facade/src/main/scala/react/semanticui/collections/grid/GridRow.scala
facade/src/main/scala/react/semanticui/collections/grid/package.scala
facade/src/test/scala/react/semanticui/collections/grid/GridRowTests.scala

Add missing columns attribute to GridRow

---

facade/src/test/scala/react/semanticui/addons/select/SelectTests.scala

Test for select

---

facade/src/main/scala/react/semanticui/widths.scala

Map of width numbers to widths

---

.scalafmt.conf
facade/src/main/scala/react/semanticui/modules/popup/Popup.scala
facade/src/main/scala/react/semanticui/package.scala

Reformat and upgrade scalafmt

---

build.sbt
demo/src/main/scala/react/semanticui/demo/SUIMain.scala
facade/src/main/scala/react/semanticui/addons/select/Select.scala
facade/src/main/scala/react/semanticui/collections/form/FormDropdown.scala
facade/src/main/scala/react/semanticui/collections/form/FormSelect.scala
facade/src/main/scala/react/semanticui/modules/dropdown/Dropdown.scala
facade/src/main/scala/react/semanticui/modules/tab/Tab.scala
facade/src/test/scala/react/semanticui/modules/sidebar/SidebarTests.scala

Update to scala 2.13.3

---

build.sbt
demo/src/main/resources/prod.js
demo/src/main/resources/theme/semantic.less
demo/src/main/resources/theme/theme.config
demo/yarn.lock

Experiment using fomantic ui, note the changes only apply to demo

Use fomantic ui

---

CHANGELOG.md
build.sbt

It seems there are no big changes that require updates to the facade

Upgrade to react semantic ui 1.0

---

CHANGELOG.md
build.sbt
facade/src/main/scala/react/semanticui/modules/dropdown/DropdownText.scala
facade/src/test/scala/react/semanticui/addons/select/SelectTests.scala
facade/src/test/scala/react/semanticui/collections/form/FormDropdownTests.scala
facade/src/test/scala/react/semanticui/collections/form/FormSelectTests.scala
facade/src/test/scala/react/semanticui/modules/dropdown/DropdownTests.scala
facade/src/test/scala/react/semanticui/modules/dropdown/DropdownTextTests.scala

Upgrade SUIR and add DropdownText

---

CHANGELOG.md
build.sbt

Upgrade SUIR

---

.github/workflows/scala.yml
.scalafmt.conf
build.sbt
demo/yarn.lock
facade/src/main/scala/react/semanticui/addons/confirm/Confirm.scala
facade/src/main/scala/react/semanticui/addons/portal/Portal.scala
facade/src/main/scala/react/semanticui/addons/portal/PortalInner.scala
facade/src/main/scala/react/semanticui/addons/radio/Radio.scala
facade/src/main/scala/react/semanticui/addons/textarea/TextArea.scala
facade/src/main/scala/react/semanticui/collections/form/FormButton.scala
facade/src/main/scala/react/semanticui/collections/form/FormCheckbox.scala
facade/src/main/scala/react/semanticui/collections/form/FormDropdown.scala
facade/src/main/scala/react/semanticui/collections/form/FormField.scala
facade/src/main/scala/react/semanticui/collections/form/FormInput.scala
facade/src/main/scala/react/semanticui/collections/form/FormTextArea.scala
facade/src/main/scala/react/semanticui/collections/menu/Menu.scala
facade/src/main/scala/react/semanticui/collections/menu/MenuItem.scala
facade/src/main/scala/react/semanticui/collections/message/Message.scala
facade/src/main/scala/react/semanticui/elements/input/Input.scala
facade/src/main/scala/react/semanticui/elements/list/List.scala
facade/src/main/scala/react/semanticui/elements/list/ListItem.scala
facade/src/main/scala/react/semanticui/modules/checkbox/Checkbox.scala
facade/src/main/scala/react/semanticui/modules/dimmer/DimmerInner.scala
facade/src/main/scala/react/semanticui/modules/dropdown/Dropdown.scala
facade/src/main/scala/react/semanticui/modules/dropdown/DropdownItem.scala
facade/src/main/scala/react/semanticui/modules/modal/Modal.scala
facade/src/main/scala/react/semanticui/modules/modal/ModalActions.scala
facade/src/main/scala/react/semanticui/modules/popup/Popup.scala
facade/src/main/scala/react/semanticui/modules/tab/Tab.scala
facade/src/main/scala/react/semanticui/views/card/Card.scala

Updates several upstream libraries and fixes a test build error
It also updates scalafmt that's why so many changes

Upgrade libraríes

---

CHANGELOG.md
build.sbt

Next version

---

CHANGELOG.md
build.sbt
demo/yarn.lock
facade/src/main/scala/react/semanticui/addons/textarea/TextArea.scala
facade/src/main/scala/react/semanticui/collections/form/Form.scala

Updates to the next version of SUI

Prepare next version

---

CHANGELOG.md
README.md
build.sbt
demo/yarn.lock
facade/src/main/scala/react/semanticui/elements/label/LabelGroup.scala
facade/src/main/scala/react/semanticui/modules/popup/Popup.scala
facade/src/test/scala/react/semanticui/elements/label/LabelGroup.scala
facade/test.webpack.config.js

Update to SUIR 2.0.0 and add facade for LabelGroup

---

CHANGELOG.md
build.sbt
facade/src/main/scala/react/semanticui/modules/popup/Popup.scala

Upgrade semantic ui react

---

build.sbt
facade/src/main/scala/react/semanticui/package.scala

Generalize the shorthand type to include any component

---

facade/src/main/scala/react/semanticui/modules/modal/Modal.scala

Make modal close icon a shorthand
